name: Créer un APK Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer le JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Rendre Gradlew exécutable
        run: chmod +x ./gradlew

      - name: Construire l'APK
        run: ./gradlew assembleDebug

      - name: Télécharger l'APK généré
        uses: actions/upload-artifact@v3
        with:
          name: ODECA-APK
          path: app/build/outputs/apk/debug/*.apk
