name: Build Android APK (Flutter)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: joscha/setup-flutter@v1
      with:
        flutter-version: "3.24.0"

    - name: Flutter version
      run: flutter --version

    - name: Get pub dependencies
      working-directory: odeca_app
      run: flutter pub get

    - name: Create Android folders if missing
      working-directory: odeca_app
      run: flutter create .

    - name: Build APK (release)
      working-directory: odeca_app
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: odeca-apk
        path: odeca_app/build/app/outputs/flutter-apk/app-release.apk
